name: Publish Build to Github Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual trigger

jobs:
  publish-release:
    permissions:
      contents: write  # allow to create a release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "${{ steps.date.outputs.NOW }}"
          automatic_release_tag: "latest"
          draft: false
          prerelease: false
          title: "org.dynapi.dynapi"
          files: |
            build/libs/*
